version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - gradle build
      - echo build

  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - board-0.0.1-SNAPSHOT.jar

cache:
  paths:
    - path
    - path
